name: NavyCraft
main: com.maximuspayne.navycraft.NavyCraft
version: 2.0.4-SNAPSHOT
authors: [Maximuspayne, Premejo, SycoPrime, Yogoda]
depend: [WorldGuard,WorldEdit,Essentials]

commands:
   navycraft:
      description: Ship and other vehicle based commands
      usage:
           /<command>
   ship:
      description: Ship
   aircraft:
      description: Aircraft
   submarine:
      description: Submarine